### ISSUE TITLE
skulls and most treasure not showing up

### ISSUE THREAD

**Issue by shark873** [xTeJk/SoT_ESP#1]
As title says most treasures and skulls are not showing up, only mermaid gems are showing up and extra stuff(like ammo crates, storage crates and etc) and yes Offsets are updated to last version 2.0.12:

{
    "AActor.HealthComponent": 2120,
    "AActor.PlayerState": 1072,
    "AActor.WieldedItemComponent": 2080,
    "AActor.actorId": 24,
    "AActor.rootComponent": 368,
    "ABootyItemInfo.BootyType": 1352,
    "ABootyItemInfo.Rarity": 1580,
    "ACrewService.Crews": 1496,
    "AFauna.Name": 2104,
    "AItemInfo.UItemDesc": 1128,
    "AItemProxy.AItemInfo": 1488,
    "AMapTable.MapPins": 1256,
    "AMapTable.ServerCenter": 1224,
    "AMapTable.TrackedShips": 1196,
    "APlayerCameraManager.CameraCache": 1152,
    "APlayerController.CameraManager": 1184,
    "APlayerController.ControlRotation": 684,
    "APlayerController.Pawn": 1048,
    "APlayerState.PlayerName": 1048,
    "AShip.CrewOwnershipComponent": 1920,
    "AWieldableItem.ItemInfo": 1464,
    "UCrewOwnershipComponent.CrewId": 212,
    "UGameInstance.LocalPlayers": 56,
    "ULocalPlayer.PlayerController": 48,
    "UWieldedItemComponent.WieldedItem": 656,
    "UWorld.OwningGameInstance": 448,
    "UWorld.PersistentLevel": 48
}

Seems that you used gummy8unny esp as source for your esp, so i tried his and on his all treasure are showing with the update offsets, but i prefer yours since its more polished

**Comment by xTeJk** [comment]
ESP wont longer be supported and updated.
