### ISSUE TITLE
How to change hotkeys

### ISSUE THREAD

**Issue by TonyDong51089** [xTeJk/SoT_ESP#3]
My keyboard does not have numpad. can I reassign num keys to some other keys?

**Comment by xTeJk** [comment]
Use the on-screen keyboard or Main.cpp file to replace:
```
KeyToggle toggleNUM1(VK_NUMPAD1);
KeyToggle toggleNUM2(VK_NUMPAD2);
KeyToggle toggleNUM3(VK_NUMPAD3);
KeyToggle toggleNUM4(VK_NUMPAD4);
KeyToggle toggleNUM5(VK_NUMPAD5);
KeyToggle toggleNUM6(VK_NUMPAD6);
KeyToggle toggleNUM7(VK_NUMPAD7);
KeyToggle toggleNUM8(VK_NUMPAD8);
KeyToggle toggleNUM9(VK_NUMPAD9);
```

at one of selected by yourself virtual-key code from this list:
https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes

For example:
`0x39` - 9

`KeyToggle toggleNUM1(0x39);`
From now on numpad1 will be started by 9

**Comment by TonyDong51089** [comment]
Thanks, much appreciate
