### ISSUE TITLE
Can it still be used now?

### ISSUE THREAD

**Issue by bbhxwl** [xTeJk/SoT_ESP#4]
Can it still be used now?

**Comment by bbhxwl** [comment]
I can only C# ，not c + +. If there is a release version, I want to try it directly

**Comment by xTeJk** [comment]
Nah, there's not release version, code needs to be updated because its outdated.

**Comment by bbhxwl** [comment]
May I ask, will you maintain it? Does this software read game memory?

**Comment by xTeJk** [comment]
I am not going to keep updating this cheat and yes, it reads process data and game memory.

**Comment by bbhxwl** [comment]
How do you learn to find memory offset? Can you point out what website it is? I'm Chinese. This game is quite popular recently. I want to study it. thank you

**Comment by xTeJk** [comment]
You need to find some tutorial how to use ReadProcessMemory. For example: https://www.unknowncheats.me/forum/programming-for-beginners/316610-properly-readprocessmemory-cheating-programs-performance.html

**Comment by bbhxwl** [comment]
Thank you for helping me. I'll use C ා to read and write memory. I'll only look up the game blood volume, such as the number of Plants vs. zombie sunlight, which is based on the most basic number. I don't know anything else. I don't know where to study

**Comment by bbhxwl** [comment]
Thank you for helping me. I'll use C#  to read and write memory. I'll only look up the game blood volume, such as the number of Plants vs. zombie sunlight, which is based on the most basic number. I don't know anything else. I don't know where to study

**Comment by bbhxwl** [comment]
How to register an account with unknown branches? Can't speak?

**Comment by xTeJk** [comment]
I dont know what do you mean, if you want to learn how to read and write memory find some tutorials for exampel at unknowncheats.
